---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-kernel
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift kernel-hack"
spec:
  workspaces:
    - name: kubeconfig-dir
      optional: true
      description: >-
        The workspace which contains the the kubeconfig file if in case we want to run the oc command on another cluster.
  description: >-
    This task runs commands against the cluster provided by user
    and if not provided then where the Task is being executed.

  params:
    - name: rpms_node_role
      type: string
    - name: remove_packages
      type: string
      default: ""
    - name: rpms_src
      type: string
  steps:
    - name: kernel
      image: quay.io/jnunez/oc-cli:latest
      script: |
        #!/usr/bin/env bash
        [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
        [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
        export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig && \
        cd $(workspaces.kubeconfig-dir.path)

        oc project testharness-kernel
        RPMS_NODE_ROLE='$(params.rpms_node_role)' \
        REMOVE_PACKAGES='$(params.remove_packages)' \
        RPMS_SRC='$(params.rpms_src)' \
        ./hack/custom_rpms.sh make custom-rpms       